#!/bin/bash

echo "🔐 Setting up Firebase CI Token for GitHub Actions"
echo "================================================="
echo ""

echo "Step 1: Generate Firebase CI Token"
echo "Run this command to generate a CI token:"
echo ""
echo "npx firebase-tools login:ci"
echo ""
echo "This will:"
echo "1. Open your browser for authentication"
echo "2. Generate a CI token"
echo "3. Display the token (copy it!)"
echo ""

echo "Step 2: Add Token to GitHub Repository"
echo "1. Go to your GitHub repository: https://github.com/lightstreamfinanceoliverinc-ai/web"
echo "2. Click 'Settings' tab"
echo "3. Click 'Secrets and variables' → 'Actions'"
echo "4. Click 'New repository secret'"
echo "5. Name: FIREBASE_TOKEN"
echo "6. Value: [paste the token from step 1]"
echo "7. Click 'Add secret'"
echo ""

echo "Step 3: Test Automatic Deployment"
echo "After adding the secret:"
echo "1. Make any change to your code"
echo "2. git add ."
echo "3. git commit -m 'Test auto-deployment'"
echo "4. git push origin main"
echo "5. Check GitHub Actions tab to see deployment progress"
echo ""

echo "✅ Once set up, every push to main will automatically:"
echo "   - Build your functions"
echo "   - Deploy to Firebase Hosting"
echo "   - Update your live website"
echo "   - Send email notifications"
echo ""

echo "🚀 Your website will auto-update on every git push!"
